### ISSUE TITLE
Send data and change tags in one request

### ISSUE THREAD

**Issue by matejsuchanek** [vlsergey/WE-Framework#50]
Tools can now send data and set tags using `tags=` in one request. This will reduce the number of log entries at https://www.wikidata.org/wiki/Special:Log/tag and make it more usable.

**Comment by vlsergey** [comment]
@matejsuchanek , i've added tags argument to wbeditentity API call.

But it seems tags are not returned on next query revisions call, so additional calls to tag method will sometimes present. It seems it is not important, because log is not populated in this case (when set already existing tag).

Currently let's wait a couple of days to check log population.

**Comment by matejsuchanek** [comment]
Thanks for the patch! I can see new edits with the tag but no new log entries. I wonder if the issue you are describing couldn't just be the delay of propagating a change to read database.
